### ISSUE TITLE
maybe bug in testsession.txt - endless loop if made a session with mistress before

### ISSUE THREAD

**Issue by Cursor10** [GodDragoner/Spicy-Tease-AI-personality-#100]
Hi, with the aktually version, i have a endless loop. I can't chose any points in main menue. I would directly redirect to session with mistress.

After it, i get everytime a notice, i hab a session before.

**Comment by MNevs** [comment]
Bye me the same, I open it Tease Ai with spicy and it automatically open a session or the firsttime script. I thought it is a problem with my tease Ai but when you have it also

**Comment by Gormagleypir** [comment]
Same, bug is in GNMBackgroundBase.txt am reading it over.

**Comment by Gormagleypir** [comment]
Found the bug.

(NoWelcome) is missing in line15 in the interrupt GNMBackgroundBase.txt

**Comment by MNevs** [comment]
Please make a pull request

**Comment by Gormagleypir** [comment]
Was the opposite that was the problem, The new (NoWelcome) that was added was making it bug out. Not sure why though, might be a Tease AI problem. But yeah made a pull request with a working version.

**Comment by GodDragoner** [comment]
Fixed
