### ISSUE TITLE
GNMSlaveModule_4ServiceTraining.txt - Script crashes after entering the amount of water being left at the end

### ISSUE THREAD

**Issue by Cursor10** [GodDragoner/Spicy-Tease-AI-personality-#82]

**Comment by GodDragoner** [comment]
Could you maybe provide the last part of the chat so I can kinda see where it ends for you?

**Comment by Cursor10** [comment]
Hi,
gladly i had make a screenshot, maybe it help you.
![exercise](https://user-images.githubusercontent.com/34005269/34358520-b49c9a54-ea50-11e7-98ca-093ae1f0c45b.jpg)

**Comment by GodDragoner** [comment]
That is the end module not the service training one :P

**Comment by MNevs** [comment]
fixed you can close
