### ISSUE TITLE
(/CR/End/ChastityTraining/BasicChastityExercise.txt)  Chastity Tasks had always 0 hours Time ( Maybe error in Random Option ?)

### ISSUE THREAD

**Issue by Cursor10** [GodDragoner/Spicy-Tease-AI-personality-#91]
I had often in the last days, that no time was calculated. Today i had following conversation as sample...

> 05:50 Charlotte Springer: Have you completed the last assignment I gave you? 
05:50 Subbie: yes
05:51 Charlotte Springer: Good 
05:51 Charlotte Springer: Let me just update your exp and reward you with lock up points.. 
05:51 Charlotte Springer: I updated your exp and points.. 
05:52 Charlotte Springer: Your chastity level is 15 
05:53 Charlotte Springer: For your next task 
05:53 Charlotte Springer: You are to wear your nasty tiny cage whenever you are home and **_for at least 0 hours in total_** 
05:53 Charlotte Springer: It's okay if you can't sleep in it

**Comment by GodDragoner** [comment]
Should be fixed with the newest update
